### ISSUE TITLE
pu

### ISSUE THREAD

**Issue by Harzva** [wqshmzh/CANet-CZSL#2]

**Comment by Harzva** [comment]
I found that this task  does not use multiple gpu training ，why? thank you very much.

**Comment by wqshmzh** [comment]
因为显存使用得很少，没必要用多卡

**Comment by Harzva** [comment]
open word 的设置用显存还是很多的，尤其是cgqa大数据集都跑不起来。

**Comment by wqshmzh** [comment]
这个工作是closed world，如果要用于open world，可以自己写一个多卡的代码，推荐使用ddp，另外计算准确度时要手动将多进程上的score矩阵gather起来再计算指标结果

**Comment by Harzva** [comment]
感谢，再实验的过程中 open world 给自己带来了极大的不方便，目前打算放弃open world实验了，只做closed world。
