### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1048576x1 and 512x512)

### ISSUE THREAD

**Issue by Vanguitar** [wqshmzh/CANet-CZSL#7]
Hi Qingsheng,

I tracked the code and the x in `**self.image_embedder_attr(x)**` was (N, 512, 1, 1) as below, not was (N*512, 1):
![image](https://github.com/wqshmzh/CANet-CZSL/assets/115961895/39c4f3b9-af63-4bd3-a5d0-d7d61ae5f05b)
![image](https://github.com/wqshmzh/CANet-CZSL/assets/115961895/957b4c38-588b-45a3-9eef-7a0335b97039)

So it's confused when the x was flattened. Could you guide this? Thank you.

**Comment by wqshmzh** [comment]
Just squeeze the x to (batch_size, 512) is OK. Remove those 1 length dimensions.

**Comment by wqshmzh** [comment]
I have uploaded the required "resnet18_feature_vectors.t7" onto Google Drive and Baidu Netdisk for all three datasets. Check the ReadMe.md. Just squeeze the x to (batch_size, 512) to remove all dimensions whose lengths are 1 and you are good to go.

**Comment by Vanguitar** [comment]
Really appreciate your comment
